.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WAITRON" "1" "December 2016" "" "Windowchef Manual"
.
.SH "NAME"
\fBwaitron\fR \- A client for windowchef(1)
.
.SH "SYNOPSIS"
\fBwaitron\fR [\-h] \fIcommand\fR [\fIargs\fR\.\.\.]
.
.SH "DESCRIPTION"
\fBwaitron\fR is the client for windowchef(1)\. It sends a given command to windowchef(1) as an X client message\. As a result, \fBwaitron\fR doesn\'t print anything on \fBstdout\fR\.
.
.SH "OPTIONS"
.
.TP
\fB\-h\fR
Print usage and version information\.
.
.SH "COMMON DEFINITIONS"
.
.TP
\fBPOSITION\fR
topleft | topright | bottomleft | bottomright | middle
.
.TP
\fBBOOL\fR
true values: \fBtrue\fR | \fBt\fR | \fByes\fR | \fBy\fR | \fB1\fR
.
.IP
false values: \fBfalse\fR | \fBf\fR | \fBno\fR | \fBn\fR | \fB0\fR
.
.SH "COMMANDS"
.
.TP
\fBwindow_move\fR \fIx\fR \fIy\fR
Move the focused window \fIy\fR pixels horizontally and \fIy\fR pixels vertically\.
.
.TP
\fBwindow_move_absolute\fR \fIx\fR \fIy\fR
Move the focused window to the position given by \fIx\fR and \fIy\fR\.
.
.TP
\fBwindow_resize\fR \fIx\fR \fIy\fR
Resize the focused window based on the relative pixel values \fIx\fR and \fIy\fR\.
.
.TP
\fBwindow_resize_absolute\fR \fIwidth\fR \fIheight\fR
Resize the focused window up to \fIwidth\fR and \fIheight\fR\.
.
.TP
\fBwindow_maximize\fR
Hide the border and maximize the focused window on the current monitor\. Execute it again after maximizing to revert the state of the window\.
.
.TP
\fBwindow_hor_maximize\fR
Horizontally maximize the focused window on the current monitor, preserving its \fIx\fR component\. Leaves a gap at the left and right of the monitor that can be configured\. Execute it again after maximizing to revert the state of the window\.
.
.TP
\fBwindow_ver_maximize\fR
Vertically maximize the focused window on the current monitor, preserving its \fIy\fR component\. Leaves a gap at the top and bottom of the monitor whose width can be configured\. Execute it again after maximizing to revert the state of the window\.
.
.TP
\fBwindow_monocle\fR
Puts the window in the "monocled" state: full screen but with borders visible\. Monocle mode respects gaps\.
.
.TP
\fBwindow_close\fR
Closes the focused window\.
.
.TP
\fBwindow_put_in_grid\fR \fIgrid_width\fR \fIgrid_height\fR \fIcell_x\fR \fIcell_y\fR
Moves and resizes the focused windows accordingly to fit in a cell defined by the \fIcell_x\fR and \fIcell_y\fR coordinates in a virtual grid with width \fIgrid_width\fR and height \fIgrid_height\fR on the current monitor\. Gaps around the windows in the grid can be added along with monitor gaps\.
.
.TP
\fBwindow_snap\fR \fIPOSITION\fR
Snap the window on the screen in a position defined by \fIPOSITION\fR\.
.
.TP
\fBwindow_cycle\fR
Cycle through mapped windows\.
.
.TP
\fBwindow_rev_cycle\fR
Reverse cycle through mapped windows\.
.
.TP
\fBwindow_cycle_in_group\fR
Cycle trough mapped windows that belong to the same group as the focused window\.
.
.TP
\fBwindow_rev_cycle_in_group\fR
Reverse cycle through mapped windows that belong to the same group as the focused window\.
.
.TP
\fBwindow_focus\fR \fIid\fR
Focus window by \fIid\fR\. The \fIid\fR can be found using pfw(1) or lsw(1) from wmutils \fIhttps://github\.com/wmutils/core/\fR\.
.
.TP
\fBgroup_add_window\fR \fIgroup_nr\fR
Add the focused window to the \fIgroup_nr\fR group\.
.
.IP
Group numbers start from 0 and end at \fIGROUPS_NO\fR \- 1\.
.
.TP
\fBgroup_remove_window\fR
Remove the focused window from its current group\.
.
.TP
\fBgroup_activate\fR \fIgroup_nr\fR
Map all windows that belong to the \fIgroup_nr\fR group\.
.
.TP
\fBgroup_deactivate\fR \fIgroup_nr\fR
Unmap all windows that belong to the \fIgroup_nr\fR group\.
.
.TP
\fBgroup_toggle\fR \fIgroup_nr\fR
Toggle the \fIgroup_nr\fR group\.
.
.TP
\fBgroup_activate_specific\fR \fIgroup_nr\fR
Activate group \fIgroup_nr\fR and deactivate the rest\.
.
.TP
\fBwm_quit\fR \fIexit_status\fR
Quit windowchef with exit_status \fIexit_status\fR\.
.
.TP
\fBwm_change_number_of_groups\fR \fInumber_of_groups\fR
Change the number of maximum groups to \fInumber_of_groups\fR\.
.
.IP
Windows that belong to a group that has a \fIgroup_nr\fR greater or equal to \fInumber_of_groups\fR will become orphaned\.
.
.TP
\fBwm_config\fR \fIkey\fR [\fIvalues\fR\.\.\.]
See \fICONFIGURING\fR\.
.
.SH "QUERYING"
Information about the current state of windowchef is made available through X properties of the root window\. Example:
.
.IP "" 4
.
.nf

xprop \-root WINDOWCHEF_ACTIVE_GROUPS
.
.fi
.
.IP "" 0
.
.P
Here is a list of exposed properties:
.
.TP
\fBWINDOWCHEF_ACTIVE_GROUPS\fR
An integer list of currently active groups\.
.
.SH "CONFIGURING"
Configuring is done using the \fBwm_config\fR command\. Possible configuration keys are:
.
.TP
\fBborder_width\fR \fIwidth\fR
Sets the border width to \fIwidth\fR pixels\.
.
.TP
\fBcolor_focused\fR, \fBcolor_unfocused\fR \fIcolor\fR
Sets the border color to \fIcolor\fR for the focused and unfocused state respectively\. \fIcolor\fR is a hexadecimal value that may or may not start with \fB0x\fR prefix\. Example: \fB0x1234ef\fR\.
.
.TP
\fBgap_width\fR \fIPOSITION\fR \fIwidth\fR
Sets the window gap at \fIPOSITION\fR to \fIwidth\fR\. \fIPOSITION\fR can be equal to \fBall\fR to set all gaps to \fIPOSITION\fR\.
.
.TP
\fBgrid_gap_width\fR \fIwidth\fR
Sets the window gap value used in virtual grids to \fIwidth\fR\.
.
.TP
\fBcursor_position\fR \fIPOSITION\fR
Sets the position of the cursor when moving or resizing windows\.
.
.TP
\fBgroups_nr\fR \fInr\fR
Sets the number of groups to \fInr\fR\. If \fInr\fR is less than the current number of groups, window that belong to groups whose numbers are greater than \fInr\fR will be mapped to screen and assigned to the null group\.
.
.TP
\fBenable_sloppy_focus\fR \fIBOOL\fR
Enable sloppy focus\.
.
.TP
\fBsticky_windows\fR \fIBOOL\fR
If \fIsticky_windows\fR is true, new windows will be assigned to the last activated group automatically\. Recommended for people who like using workspaces over groups\.
.
.TP
\fBenable_borders\fR \fIBOOL\fR
If true, border colors will be set each time a window gets/loses focus\. Setting it to false is useful when using another program to draw the borders (example: \fBchwb2\fR from wmutils)\.
.
.SH "SEE ALSO"
windowchef(1), sxhkd(1), wmutils(1), pfw(1), lsw(1), chwb2(1), lemonbar(1)
.
.SH "AUTHOR"
Tudor Roman \fB<tudurom at gmail dot com>\fR
