#!/bin/sh -x

ROOT=`lsw -r`
DW=`wattr w $ROOT`
DH=`wattr h $ROOT`

CB=`xrq '*.background'`
CF=`xrq '*.foreground'`
BW=$(( DW - 700 ))
BH=30
BX=$(( (DW - BW) / 2 ))
BY=20

OPTS="-g ${BW}x${BH}+${BX}+${BY} -F $CF -B $CB"

doit() {
	echo "windowchef showcase"
	sleep 0.3

	echo "bye"
	sleep 1
}

doit | lemonbar $OPTS
