#!/bin/sh

./waitron wm_config border_width 5
./waitron wm_config color_focused 0x97a293
./waitron wm_config color_unfocused 0x393638
./waitron wm_config gap_width all 20
./waitron wm_config cursor_position middle
./waitron wm_config groups_nr 4
./waitron wm_config enable_sloppy_focus true
./waitron wm_config sticky_windows false
./waitron wm_config enable_borders true
